config:
  credentials:
  - id: https://github.com/PalomoIFCA/private-sqaaastesting
    password_var: gAAAAABpCyGK0cOcmLK0C9On_aEivkKuAC-DWOLuNY-C7yYZvgrnRtSVIzb2CvUN-zP3_k756QNFWRfE9Ze0tX-Fp3pghIREHjISRsMnM7QMuJSlmA2u_BIN-Wn47lfcudfnEcotu8sX
    username_var: gAAAAABpCyGKvM65YHxSEpjEZ1ZZBG4qYr-WlXxuA9Vxjc_f0IzsnI4_GEpUyflcN3g7srEZwJ00utireKCmSd5aid5pFpNCbA==
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/private-sqaaastesting:
      branch: main
      credential_tmp: true
      repo: https://github.com/PalomoIFCA/private-sqaaastesting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-ivory-birman.sh
        container: qc.acc_flaky-periwinkle-spitz
  QC.Doc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-cinnabar-rat.sh
        container: qc.doc_messy-amethyst-tapir
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-black-ferret.sh
        container: qc.doc_trippy-puce-horse
      github.com/PalomoIFCA/private-sqaaastesting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-red-leopard.sh
        container: qc.doc_frumpy-white-sheep
  QC.Lic:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-green-rottweiler.sh
        container: qc.lic_grumpy-magenta-whippet
  QC.Sec:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-flax-gorilla.sh
        container: qc.sec_stuffy-sepia-armadillo
  QC.Sty:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-harlequin-capuchin.sh
        container: qc.sty_nerdy-amethyst-binturong
  QC.Uni:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-copper-shrimp.sh
        container: qc.uni_leaky-fuchsia-ocelot
  QC.Ver:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-malachite-leopard.sh
        container: qc.ver_flaky-zucchini-mammoth
timeout: 5400
