config:
  credentials:
  - id: https://github.com/PalomoIFCA/private-sqaaastesting
    password_var: gAAAAABpZ1JgAJ7XowmLUMWhP5eDvFyzM4_ohVLP3GUKALluchVm06DJb3NDgkOo3W4xuxMzLRXf2LWJAOcoOlkuRqHeyl4oyQpvjactfNbvQN4pjmimKQ52VoRSqk-q1iYt06FjE0VW
    username_var: gAAAAABpZ1JgVBDE6PyVgs1LguuhNKsk83REmt_-Qspgc7_Y0os41SwHcIUqnbEKUB84dHpb5SP4Lq6D_HwZicF-i3ikVgYeRA==
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/private-sqaaastesting:
      branch: main
      credential_tmp: true
      repo: https://github.com/PalomoIFCA/private-sqaaastesting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-salmon-moth.sh
        container: qc.acc_hazy-violet-llama
  QC.Doc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-goldenrod-quoll.sh
        container: qc.doc_greasy-cerulean-rhinoceros
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-malachite-blue.sh
        container: qc.doc_squirrely-amaranth-dolphin
      github.com/PalomoIFCA/private-sqaaastesting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-amethyst-butterfly.sh
        container: qc.doc_woozy-gamboge-paradise
  QC.Lic:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homely-flax-snail.sh
        container: qc.lic_whiny-salmon-bee
  QC.Sec:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting bandit:
        commands:
        - /usr/bin/env sh .sqa/script.silly-plum-malamute.sh
        container: qc.sec_tasty-sapphire-burmese
  QC.Sty:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting flake8:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-gamboge-chicken.sh
        container: qc.sty_crappy-chestnut-termite
  QC.Uni:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting pytest:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-magnolia-magpie.sh
        container: qc.uni_homely-bronze-bracke
  QC.Ver:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-platinum-pinscher.sh
        container: qc.ver_sleepy-lavender-scorpion
timeout: 5400
