config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/private-sqaaastesting:
      branch: main
      credential_tmp: true
      repo: https://github.com/PalomoIFCA/private-sqaaastesting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-cerise-earwig.sh
        container: qc.acc_lumpy-sepia-shrew
  QC.Doc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-champagne-barb.sh
        container: qc.doc_pasty-goldenrod-spoonbill
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-dandelion-flounder.sh
        container: qc.doc_shabby-myrtle-macaw
      github.com/PalomoIFCA/private-sqaaastesting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-lemon-octopus.sh
        container: qc.doc_snazzy-viridian-oyster
  QC.Lic:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-khaki-quail.sh
        container: qc.lic_skanky-peach-beaver
  QC.Sec:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting bandit:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-salmon-reindeer.sh
        container: qc.sec_geeky-malachite-termite
  QC.Sty:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-cardinal-rabbit.sh
        container: qc.sty_skanky-platinum-hummingbird
  QC.Uni:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting pytest:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-mauve-capybara.sh
        container: qc.uni_cloudy-puce-collie
  QC.Ver:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-chartreuse-alligator.sh
        container: qc.ver_grumpy-bistre-wolverine
timeout: 5400
