config:
  credentials:
  - id: https://github.com/PalomoIFCA/private-sqaaastesting
    password_var: gAAAAABpZjF99zM3iB-Tg4MiT-mqw6ON-22IAtWY3lTqmh317EPUKHTn36mXmnbBSI4gm4PuvegOMZuUpjlkw2uL2Hs_Z_auHZ8IlViDY6Cy08V0_K5yPpNYUmUTxSmM3-t-WZCHPqkO
    username_var: gAAAAABpZjF9_mb7yna_Je4OdBVCiND6C1N6J3Z3seB_SjoeEQGfbE0nTuTXiDEvkT3bNIRADrv5aJEeITpT0oRL6r_pYfD1Dw==
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/private-sqaaastesting:
      branch: main
      credential_tmp: true
      repo: https://github.com/PalomoIFCA/private-sqaaastesting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-black-tarantula.sh
        container: qc.acc_chummy-bistre-shrew
  QC.Doc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-ruby-barb.sh
        container: qc.doc_stinky-chartreuse-newt
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-aquamarine-tarsier.sh
        container: qc.doc_baggy-saffron-walrus
      github.com/PalomoIFCA/private-sqaaastesting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-ivory-terrier.sh
        container: qc.doc_goopy-rose-sheep
  QC.Lic:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-chocolate-chicken.sh
        container: qc.lic_cozy-champagne-sheep
  QC.Sec:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting bandit:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-sangria-pig.sh
        container: qc.sec_muggy-peach-cow
  QC.Sty:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-corn-coyote.sh
        container: qc.sty_sloppy-scarlet-seahorse
  QC.Uni:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-apricot-loon.sh
        container: qc.uni_cranky-amethyst-eagle
  QC.Ver:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-tomato-avocet.sh
        container: qc.ver_skimpy-corn-lemur
timeout: 5400
