config:
  credentials:
  - id: https://github.com/PalomoIFCA/private-sqaaastesting
    password_var: gAAAAABpZ1ToYJWWqv2o8uaRJ_SkgHzrkAyZKrUoh5xO7_S6Iu8ARcvw-Csc7an1yq_0cjUQzB7gY0roovYX8sr956B6T9DP5EHM9x9XIzcPy5Yxo1Xzr7NM6P068yFlSLnxzD48vpsY
    username_var: gAAAAABpZ1TodC7U3MzFcy5BMwXIJ33UMsoLBCP2FAelR_3pwGxZM987Ta37eVmOHkMB6ql0claYB7KieOdFWXES74wyrUz1Fg==
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/private-sqaaastesting:
      branch: main
      credential_tmp: true
      repo: https://github.com/PalomoIFCA/private-sqaaastesting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-cinnabar-mule.sh
        container: qc.acc_muggy-cardinal-booby
  QC.Doc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-ochre-squirt.sh
        container: qc.doc_bumpy-flax-binturong
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-aquamarine-tuatara.sh
        container: qc.doc_tasty-chartreuse-squirt
      github.com/PalomoIFCA/private-sqaaastesting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-tangerine-wallaby.sh
        container: qc.doc_shaggy-myrtle-yak
  QC.Lic:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-yellow-squirrel.sh
        container: qc.lic_sunny-blue-quetzal
  QC.Sec:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-brass-bulldog.sh
        container: qc.sec_homey-firebrick-dachsbracke
  QC.Sty:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting flake8:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-ruby-caiman.sh
        container: qc.sty_homey-black-vulture
  QC.Uni:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting pytest:
        commands:
        - /usr/bin/env sh .sqa/script.homely-sepia-kakapo.sh
        container: qc.uni_silly-celadon-otter
  QC.Ver:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-cobalt-clam.sh
        container: qc.ver_flaky-magenta-cuttlefish
timeout: 5400
