config:
  credentials:
  - id: https://github.com/PalomoIFCA/private-sqaaastesting
    password_var: gAAAAABpoAhFhB0o12lHxJfXJto975IA2nFgsL8NVb3sGcNEDJNDIA5drOId2oO0Oa0O5duPOs3DV2NEI9zE8MIEU4B3DjQMdiZZt2GlaN3k4RU5b_jL-CgoIlNOdTF6ZsvCEUlGV9di
    username_var: gAAAAABpoAhFCGoAb4oxN3zQg6yxwrN70uoEG6iOBiR86un1L5msEKmJBSv1hyMz8wjEQT04AVs9aRZpdQ05kfng9XPttYkxFA==
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/private-sqaaastesting:
      branch: main
      credential_tmp: true
      repo: https://github.com/PalomoIFCA/private-sqaaastesting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-salmon-newt.sh
        container: qc.acc_paltry-magnolia-mau
  QC.Doc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-maroon-alligator.sh
        container: qc.doc_boozy-rust-nightingale
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-coral-oriole.sh
        container: qc.doc_sunny-green-wombat
      github.com/PalomoIFCA/private-sqaaastesting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-maroon-ragdoll.sh
        container: qc.doc_tasty-teal-scorpion
  QC.Lic:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-lime-llama.sh
        container: qc.lic_wheezy-linen-robin
  QC.Sec:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-burgundy-walrus.sh
        container: qc.sec_baggy-cerise-dunker
  QC.Sty:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-emerald-gar.sh
        container: qc.sty_snazzy-asparagus-cow
  QC.Uni:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting pytest:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-turquoise-quokka.sh
        container: qc.uni_hasty-champagne-bobcat
  QC.Ver:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-gamboge-earwig.sh
        container: qc.ver_woozy-white-dollar
timeout: 5400
