config:
  credentials:
  - id: https://github.com/PalomoIFCA/private-sqaaastesting
    password_var: gAAAAABpC0TI4jqGqi68kUb2RiZ_CaRhSXnGghcHpaRhwH4o6eOusn7e8NX8SJv8mg1TZDZmcwk93Z1QGdaGfVI5bpt-4kIoA8U6ziPD9lR5iSQ9xEY2MfXO6fCmWXCl2-eHl0JjKX6W
    username_var: gAAAAABpC0TIckG5tffZ2O7HFAJzWUAd80YYkMt-u7ilY03oMDr04ATct5F1K1RiP9a6Owq6-_MBdfRsKJMa-z6sH5g6Ts4YQQ==
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/private-sqaaastesting:
      branch: main
      credential_tmp: true
      repo: https://github.com/PalomoIFCA/private-sqaaastesting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-crimson-barb.sh
        container: qc.acc_beady-cobalt-duck
  QC.Doc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-xanthic-eleuth.sh
        container: qc.doc_shabby-corn-javanese
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-cobalt-fox.sh
        container: qc.doc_lanky-violet-warthog
      github.com/PalomoIFCA/private-sqaaastesting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-bronze-chihuahua.sh
        container: qc.doc_blurry-asparagus-gibbon
  QC.Lic:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-chestnut-buzzard.sh
        container: qc.lic_flimsy-orange-blue
  QC.Sec:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-olivine-mau.sh
        container: qc.sec_homey-periwinkle-opossum
  QC.Sty:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-mauve-quokka.sh
        container: qc.sty_boozy-mustard-donkey
  QC.Uni:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting pytest:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-azure-weasel.sh
        container: qc.uni_shaggy-black-harrier
  QC.Ver:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-olive-javanese.sh
        container: qc.ver_geeky-chocolate-hyena
timeout: 5400
