config:
  credentials:
  - id: https://github.com/PalomoIFCA/private-sqaaastesting
    password_var: gAAAAABpCbt5lfuyH_I07AMrw229XTYuVdJna2vmBv6kuZLfD702TkIx8FZzIWuGRjKAjI_s2xQwIe7eUHk5QBhbBHLlIr6jAzsDC-kWCqoi4wvX47hRWS0Q1r1H5oSjErq_mKtaeq9V
    username_var: gAAAAABpCbt5wkvXVpWv46j7ipE5pYOxIdh4_LxSH8XncumkBJpa9PqgtPuODJ4oznKS5cFF0y9L-xjwosY8R8faXjRPN9o2Vg==
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/private-sqaaastesting:
      branch: main
      credential_tmp: true
      repo: https://github.com/PalomoIFCA/private-sqaaastesting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-buff-javanese.sh
        container: qc.acc_snippy-lavender-insect
  QC.Doc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-crimson-mouse.sh
        container: qc.doc_shaky-asparagus-zorse
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-maroon-monkey.sh
        container: qc.doc_homely-vermilion-snake
      github.com/PalomoIFCA/private-sqaaastesting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-cerise-insect.sh
        container: qc.doc_muzzy-coral-grouse
  QC.Lic:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-copper-foxhound.sh
        container: qc.lic_silly-xanthic-horse
  QC.Sec:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting bandit:
        commands:
        - /usr/bin/env sh .sqa/script.messy-tan-buffalo.sh
        container: qc.sec_skanky-puce-gar
  QC.Sty:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting flake8:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-harlequin-yak.sh
        container: qc.sty_scaly-puce-mule
  QC.Uni:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting pytest:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-cardinal-chameleon.sh
        container: qc.uni_gimpy-chartreuse-gerbil
  QC.Ver:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-celadon-quoll.sh
        container: qc.ver_skimpy-goldenrod-mastiff
timeout: 5400
