config:
  credentials:
  - id: https://github.com/PalomoIFCA/private-sqaaastesting
    password_var: gAAAAABpoAHejuf9Ux_c49EongkBa5D0nARKAcPh-bwYPqSpGA_WJKp12N8mtP-oquE1nFixW4kXaqz1w0UxSX-yxsgTYSVBtJpiIwtgW8mQlM3kH0mhkPphR_LyvXxBXPzjaiiyg-KA
    username_var: gAAAAABpoAHeC9my4d4i6ReAi0IiQMn0V1pbjRJsX4fcWRZOLY20DnVQSHlJLkR0IiojJDW9T1ieZevtARpzaw1q4cy7bJOd6A==
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/private-sqaaastesting:
      branch: main
      credential_tmp: true
      repo: https://github.com/PalomoIFCA/private-sqaaastesting
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-beige-slug.sh
        container: qc.acc_wiggy-copper-fly
  QC.Doc:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-buff-octopus.sh
        container: qc.doc_pokey-wheat-paradise
      github.com/PalomoIFCA/private-sqaaastesting git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-cerise-bat.sh
        container: qc.doc_silly-asparagus-axolotl
      github.com/PalomoIFCA/private-sqaaastesting markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-persimmon-civet.sh
        container: qc.doc_flaky-mauve-sponge
  QC.Lic:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-sangria-nightingale.sh
        container: qc.lic_nippy-black-termite
  QC.Sec:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-champagne-peccary.sh
        container: qc.sec_snazzy-salmon-emu
  QC.Sty:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting flake8:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-fuchsia-zebu.sh
        container: qc.sty_nerdy-cobalt-buffalo
  QC.Uni:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting pytest:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-sepia-deer.sh
        container: qc.uni_crabby-burgundy-setter
  QC.Ver:
    repos:
      github.com/PalomoIFCA/private-sqaaastesting get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-taupe-bobcat.sh
        container: qc.ver_clammy-fuchsia-orangutan
timeout: 5400
